### ISSUE TITLE
Tests are failing in fresh conda environment

### ISSUE THREAD

**Issue by szgoger** [yingxingcheng/lrccd#1]
Hi,

I've set up a completely new virtual environment with conda, installed HORTON 2.3.0 from conda-forge, pytest with pip, and lrccd with pip also. 

After this, trying to run the tests returns a lot of error messages - I am attaching the error output: 
[errors.txt](https://github.com/yingxingcheng/lrccd/files/12585861/errors.txt)

For reference, the package versions are found here: 
[environ.txt](https://github.com/yingxingcheng/lrccd/files/12585874/environ.txt)

**Comment by yingxingcheng** [comment]
I’m on holiday now, but I know how to fix it. This is because some api has been changed since Horton 2.3.0. I will come back after Friday.

**Comment by yingxingcheng** [comment]
@szgoger can you try the new branch horton-2.3.0? It should work for horton-2.3.0. Please note that I tested it with Python3.11 and numpy==1.23.0.

**Comment by szgoger** [comment]
The tests seem to work with the new branch, and numpy==1.23.0 is installed automatically by pip, so probably everything is fine. I still get a lot of warnings, but nothing looks serious. I am yet to try a real calculation though - I will work on learning how to do that now.

**Comment by yingxingcheng** [comment]
okay, good to know, and I'll merge it to the main branch.
